<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class QuestionnaireResponse extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'first_name',
        'last_name',
        'phone',
        'email',
        'address',
        'age',
        // Project Information
        'sq_footage',
        'project_type',
        'established_budget',
        'how_did_you_hear',
        'worked_with_designer',
        'special_considerations',
        'services',
        'services_other',
        'working_room',
        'working_room_other',
        'project_goal',
        'inspiration_links',
        'room_activities',
        'room_users_characteristics',
        'hobbies_in_design',
        'special_needs',
        'space_goal',
        // Project Planner
        'planner_project_budget',
        'involvement_process',
        'timeframe',
        'construction_time',
        // Style Preference
        'design_style',
        'design_style_other',
        'flooring_preference',
        'flooring_preference_other',
        'window_coverings',
        'window_coverings_other',
        'color_palette',
        'decorative_elements',
        'decorative_elements_other',
        'seating_arrangement',
        'lighting_preference',
        'furniture_style',
        'dislike_color',
        'dislike_pattern',
        'shelved_type',
        'mood',
        'mood_other',
        'items_to_keep',
        // Bathroom Preference
        'bathroom_style',
        'shower_hardware',
        'heating_preference',
        'tiling_preference',
        'tiling_preference_other',
        'basin_preference',
        'basin_preference_other',
        'storing_preference',
        'storing_preference_other',
        'ventilation',
        'ventilation_other',
        // Kitchen Preference
        'kitchen_style',
        'sink_design',
        'fridge_style',
        'fridge_style_other',
        'oven_preference',
        'oven_preference_other',
        'splashback_design',
        'splashback_design_other',
        'cooking_fuel',
        'cooking_fuel_other',
        'seating_configuration',
        'seating_configuration_other',
        'storage_options',
        'storage_options_other',
        'island_yn',
        'island_yn_other',
        // Living Room Preference
        'living_room_preference',
        // Bedroom Preference
        'bedding_preference',
        'bedding_preference_other',
        'bed_size',
        'bed_size_other',
        'bedroom_lighting_preference',
        'bedroom_lighting_preference_other',
        'bedroom_storage_solutions',
        'bedroom_storage_solutions_other',
        // Furniture Preference
        'furnishings_purchase_location',
        'frequent_websites',
        'repurpose_pieces',
        'furnishing_spend',
    ];
    protected $guarded = ['id'];

    protected $casts = [
        'services' => 'array',
        'working_room' => 'array',
        'planner_project_budget' => 'array',
        'involvement_process' => 'array',
        'timeframe' => 'array',
        'construction_time' => 'array',
        'design_style' => 'array',
        'flooring_preference' => 'array',
        'window_coverings' => 'array',
        'color_palette' => 'array',
        'decorative_elements' => 'array',
        'seating_arrangement' => 'array',
        'lighting_preference' => 'array',
        'furniture_style' => 'array',
        'shelved_type' => 'array',
        'mood' => 'array',
        'bathroom_style' => 'array',
        'shower_hardware' => 'array',
        'heating_preference' => 'array',
        'tiling_preference' => 'array',
        'basin_preference' => 'array',
        'storing_preference' => 'array',
        'ventilation' => 'array',
        'kitchen_style' => 'array',
        'sink_design' => 'array',
        'fridge_style' => 'array',
        'oven_preference' => 'array',
        'splashback_design' => 'array',
        'cooking_fuel' => 'array',
        'seating_configuration' => 'array',
        'storage_options' => 'array',
        'island_yn' => 'array',
        'bedding_preference' => 'array',
        'bed_size' => 'array',
        'bedroom_lighting_preference' => 'array',
        'bedroom_storage_solutions' => 'array',
        'furnishing_spend' => 'array',
    ];
}